// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-hXOixJxHN8SzmGbS_6ofoFcsTda5rxE',
    appId: '1:1026434973310:web:1e65bce4c8a7e4dd11a22f',
    messagingSenderId: '1026434973310',
    projectId: 'ezyvoice-82869',
    authDomain: 'ezyvoice-82869.firebaseapp.com',
    storageBucket: 'ezyvoice-82869.firebasestorage.app',
    measurementId: 'G-54GN1NHDCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunojNpyAK1U_w4vJonBHOyPK6Nu45Zxk',
    appId: '1:1026434973310:android:357d42d77eabaa8111a22f',
    messagingSenderId: '1026434973310',
    projectId: 'ezyvoice-82869',
    storageBucket: 'ezyvoice-82869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhu4tg0vXc9yQ-kxat0OeM6CaWdmoBSZA',
    appId: '1:1026434973310:ios:2eebccb797a7354411a22f',
    messagingSenderId: '1026434973310',
    projectId: 'ezyvoice-82869',
    storageBucket: 'ezyvoice-82869.firebasestorage.app',
    iosBundleId: 'com.example.ezyVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhu4tg0vXc9yQ-kxat0OeM6CaWdmoBSZA',
    appId: '1:1026434973310:ios:2eebccb797a7354411a22f',
    messagingSenderId: '1026434973310',
    projectId: 'ezyvoice-82869',
    storageBucket: 'ezyvoice-82869.firebasestorage.app',
    iosBundleId: 'com.example.ezyVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-hXOixJxHN8SzmGbS_6ofoFcsTda5rxE',
    appId: '1:1026434973310:web:571747ef59e75a8611a22f',
    messagingSenderId: '1026434973310',
    projectId: 'ezyvoice-82869',
    authDomain: 'ezyvoice-82869.firebaseapp.com',
    storageBucket: 'ezyvoice-82869.firebasestorage.app',
    measurementId: 'G-1F7EB47BJZ',
  );
}
